services:
  app:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]

    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__host: ${DB_HOST}
      LISTMONK_db__port: ${DB_PORT:-5432}
      LISTMONK_db__user: ${DB_USER}
      LISTMONK_db__password: ${DB_PASSWORD}
      LISTMONK_db__database: ${DB_NAME:-postgres}
      LISTMONK_db__ssl_mode: require
      LISTMONK_db__max_open: 15
      LISTMONK_db__max_idle: 5
      LISTMONK_db__max_lifetime: 300s
      TZ: Etc/UTC
      LISTMONK_ADMIN_USER: ${LISTMONK_ADMIN_USER:-admin}
      LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:-admin}
    volumes:
      - ./uploads:/listmonk/uploads:rw